#!/bin/bash
distroCheckOne=`cat /etc/os-release | grep -i "NAME=\"Fedora"`
distroCheckTwo=`cat /etc/fedora-release | grep -i "Fedora"`
if [[ -z $distroCheckOne || -z $distroCheckTwo ]]
then
    echo "Distribution is not Fedora, exiting..."
    exit 0
fi
echo 'Performing system update'
sudo dnf update -y
if [ -x /usr/bin/flatpak ]
then
    echo 'Performing flatpaks update'
    flatpak update -y
fi
if [ -x /usr/sbin/akmods-shutdown ]
then            
    echo 'Rebuilding akmods, please wait'
    sudo akmods-shutdown
fi